name: lewisfromlewis
markdown: kramdown
theme: jekyll-theme-slate
permalink: /blog/:year/:month/:day/:title
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
